openapi: 3.0.0
info:
  title: calculator
  version: "1"
paths:
  /addition:
    get:
      parameters:
        -
          name: number1
          required: true
          in: query
          schema:
            type: integer
        -
          name: number2
          required: true
          in: query
          schema:
            type: number
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                example:
                  message: result 12
        "400":
          description: ""
          content:
            application/json:
              schema:
                example:
                  message: bad request
        "500":
          description: ""
          content:
            application/json:
              schema:
                example:
                  message: serror
